name: yeadon
channels:
- conda-forge
- default
dependencies:
    - python==3.10
    - bioviz
    - pip
    - uvicorn
    - fastapi
    - pip:
        - yeadon
        - IPython
        - rembg
        - openpifpaf
